<?php
namespace Tashevs;
include "interfaces/otasininasihatlari.php";
include "interfaces/onanasihatlari.php";
include "otaona.php";
class Farzandlari extends Otaona implements Otasininasihatlari, Onanasihatlari {
    public function otanani_avaylash(){
        echo "<hr>Farzandni burchi Ota Onani avaylab ularni sevish<hr>";
    }
    public function aka_va_ukaga_yordam_berish()
    {
        // TODO: Implement aka_va_ukaga_yordam_berish() method.
        echo "<hr>Hop boladi!!<hr>";
    }
    public function yaxshi_kasb_egalash()
    {
        // TODO: Implement yaxshi_kasb_egalash() method.
    }
    public function yaxshi_qizga_uylan()
    {
        // TODO: Implement yaxshi_qizga_uylan() method.
    }
    public function dokoni_sotib_oldik()
    {
        return parent::dokoni_sotib_oldik(); // TODO: Change the autogenerated stub
    }

}

$farzandlari = new Farzandlari();

echo $farzandlari->DoNotChangeYourReligion();
